db.driver=org.apache.derby.iapi.jdbc.AutoloadedDriver
db.url=jdbc:derby:directory:target/e2etest-derby;create=true
db.query=VALUES 1

mail.smtp.from=test@example.com
mail.smtp.host=localhost
mail.smtp.port=8025
mail.smtp.auth=false
mail.smtp.username=
mail.smtp.password=
mail.smtp.starttls.enable=false
