db.driver=org.apache.derby.iapi.jdbc.AutoloadedDriver
db.query=VALUES 1

mail.smtp.from=${EMAIL}
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.username=${EMAIL}
mail.smtp.password=${MAIL_PASSWORD}
mail.smtp.starttls.enable=true
